public without sharing class TestingStyleSheetController{

public String testInput {get; set;}
public String testInputsfdc {get; set;}


public void TestingStyleSheetController(){

    newChat();    
        
}

public void SaveInputs() {
        //testInput = '';
        System.debug('>>>>>> In save method: ' + testInput);
        }
    



public void newChat() {
        //testInput = '';
        system.debug('>>>>>> In newChat method: ' + testInput);
        }
    


}